version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=spring-graphql
    ports:
      - '5432:5432'
    volumes:
      - spring-graphql-db:/var/lib/postgresql/data
volumes:
  spring-graphql-db: